// This file is Copyright its original authors, visible in version control history.
//
// This file is licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license <LICENSE-MIT or
// http://opensource.org/licenses/MIT>, at your option. You may not use this file except in
// accordance with one or both of these licenses.

//! Bitcoin Deposits Protocol Events
//!
//! This module defines events specific to the Bitcoin Deposits protocol
//! that are emitted during protocol operations.

use bitcoin::secp256k1::PublicKey;
use lightning::impl_writeable_tlv_based_enum;

/// Events generated by Bitcoin Deposits protocol operations
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum DepositsEvent {
    // Ledger events
    /// A new ledger was created
    LedgerCreated {
        /// ledger address (as string)
        ledger_address: String,
        /// Operator's public key
        operator_key: PublicKey,
        /// Reserves identifier
        reserves_key: PublicKey,
    },

    // Deposit events
    /// A deposit was added to the ledger
    DepositAdded {
        /// Deposit public key
        pubkey: PublicKey,
    },

    /// A deposit was removed from the ledger
    DepositRemoved {
        /// Deposit public key
        pubkey: PublicKey,
    },

    /// A deposit's balance changed
    DepositBalanceChanged {
        /// Deposit public key
        pubkey: PublicKey,
        /// Previous balance
        old_balance: u64,
        /// New balance
        new_balance: u64,
    },

    // Reserve events
    /// Reserves were increased (moved from channel balance to reserves)
    ReservesIncreased {
        /// Amount increased
        amount: u64,
    },

    /// Reserves were decreased (moved from reserves back to channel balance)
    ReservesDecreased {
        /// Amount decreased
        amount: u64,
    },

    /// Insufficient reserves detected
    ReservesInsufficient {
        /// Required reserves amount
        required: u64,
        /// Available reserves amount
        available: u64,
    },

    // Commitment transaction events
    /// Lightning commitment transaction was enhanced with Bitcoin Deposits protocol elements
    CommitmentEnhanced {
        /// Partner node in the channel
        partner_node_id: PublicKey,
        /// Ledger hash included in commitment
        ledger_hash: [u8; 32],
        /// Commitment transaction number
        commitment_number: u64,
        /// Number of reserves outputs added
        reserves_outputs_count: u64,
    },

    // Payment events
    /// Invoice was cosigned and is ready for payment
    InvoiceCosigned {
        /// Invoice identifier
        invoice_id: String,
        /// Deposit that will receive payment
        deposit_pubkey: PublicKey,
        /// Invoice amount
        amount: u64,
    },

    /// Payment was credited to a deposit
    PaymentCredited {
        /// Deposit that received payment
        deposit_pubkey: PublicKey,
        /// Amount credited
        amount: u64,
    },

    /// Payment was debited from a deposit
    PaymentDebited {
        /// Deposit that sent payment
        deposit_pubkey: PublicKey,
        /// Amount debited
        amount: u64,
    },

    // Protocol violations
    /// Protocol violation detected
    ProtocolViolation {
        /// Partner node that violated protocol
        partner_node_id: PublicKey,
        /// Type of violation
        violation_type: String,
        /// Evidence of the violation
        evidence: Vec<u8>,
    },

    // Cross-ledger auditing
    /// Discrepancy found during audit
    AuditDiscrepancy {
        /// Partner node being audited
        partner_node_id: PublicKey,
        /// Ledger where discrepancy was found
        ledger_address: String,
        /// Type of discrepancy
        discrepancy_type: String,
    },

    // Fee events
    /// Fee was assessed on a deposit
    FeeAssessed {
        /// Deposit that was charged
        deposit_pubkey: PublicKey,
        /// Fee amount
        amount: u64,
        /// Assessment timestamp (seconds since Unix epoch)
        timestamp: u64,
    },

    // Transfer events
    /// Balance was locked for a transfer
    TransferLocked {
        /// Deposit that had balance locked
        deposit_pubkey: PublicKey,
        /// Amount locked
        amount: u64,
        /// Transfer identifier
        transfer_id: [u8; 32],
    },

    /// Transfer was completed successfully
    TransferCompleted {
        /// Deposit that sent the transfer
        deposit_pubkey: PublicKey,
        /// Amount transferred
        amount: u64,
        /// Transfer identifier
        transfer_id: [u8; 32],
    },

    /// Transfer failed and balance was unlocked
    TransferFailed {
        /// Deposit that had balance unlocked
        deposit_pubkey: PublicKey,
        /// Amount unlocked
        amount: u64,
        /// Transfer identifier
        transfer_id: [u8; 32],
    },

    // Cross-ledger audit events
    /// Cross-ledger audit completed
    AuditCompleted {
        /// Partner node that was audited
        partner_node_id: PublicKey,
        /// Ledger that was audited
        ledger_id: u16,
        /// Number of violations found
        violations_found: u32,
    },

    // Quorum voting events
    /// Reserves spend transaction is ready to broadcast after quorum approval
    ReservesSpendReady {
        /// Vote round ID for this spend
        vote_round_id: [u8; 32],
        /// Operator public key
        operator_id: PublicKey,
        /// Partner public key
        reserves_id: PublicKey,
        /// Fully signed transaction bytes ready for broadcast
        signed_tx_bytes: Vec<u8>,
        /// Number of conforming votes received
        conforming_votes: u32,
        /// Threshold required
        threshold: u32,
    },

    // Recovery events
    /// Recovery claim has enough signatures and is ready to broadcast
    RecoveryClaimReady {
        /// Operator public key (the non-conforming operator being recovered from)
        operator_id: PublicKey,
        /// Partner public key
        reserves_id: PublicKey,
    },

    /// Recovery claim transaction has been confirmed
    RecoveryClaimCompleted {
        /// Old operator public key (that was non-conforming)
        old_operator: PublicKey,
        /// Partner public key
        reserves_id: PublicKey,
        /// New operator public key (that took over)
        new_operator: PublicKey,
        /// Claim transaction ID
        claim_txid: [u8; 32],
        /// Block height where claim was confirmed
        confirmation_block: u32,
    },

    /// Non-compliance determined by voting - eligible partners can now initiate claims
    RecoveryNonCompliant {
        /// Operator public key (determined to be non-compliant)
        operator_id: PublicKey,
        /// Partner public key
        reserves_id: PublicKey,
        /// Number of non-conforming votes
        non_conforming_votes: u32,
        /// Total votes received
        total_votes: u32,
    },

    /// Uncredited payment accusation received - a partner claims a payment was
    /// settled (preimage revealed) but the operator never credited the wallet
    UncreditedPaymentAccusation {
        /// Operator public key (accused of not crediting)
        operator: PublicKey,
        /// Partner public key (the accuser)
        partner: PublicKey,
        /// Payment hash of the settled payment
        payment_hash: [u8; 32],
        /// Deposit that should have been credited
        deposit_pubkey: PublicKey,
        /// Amount that should have been credited
        amount_msat: u64,
        /// Ledger sequence at time of settlement
        settlement_sequence: u64,
    },
}

// For now, implement simple TLV serialization for DepositsEvent
impl_writeable_tlv_based_enum!(DepositsEvent,
	(0, LedgerCreated) => {
		(0, ledger_address, required),
		(2, operator_key, required),
		(4, reserves_key, required),
	},
	(1, DepositAdded) => {
		(0, pubkey, required),
	},
	(2, DepositRemoved) => {
		(0, pubkey, required),
	},
	(3, DepositBalanceChanged) => {
		(0, pubkey, required),
		(2, old_balance, required),
		(4, new_balance, required),
	},
	(4, ReservesIncreased) => {
		(0, amount, required),
	},
	(5, ReservesDecreased) => {
		(0, amount, required),
	},
	(6, ReservesInsufficient) => {
		(0, required, required),
		(2, available, required),
	},
	(7, InvoiceCosigned) => {
		(0, invoice_id, required),
		(2, deposit_pubkey, required),
		(4, amount, required),
	},
	(8, PaymentCredited) => {
		(0, deposit_pubkey, required),
		(2, amount, required),
	},
	(9, PaymentDebited) => {
		(0, deposit_pubkey, required),
		(2, amount, required),
	},
	(10, ProtocolViolation) => {
		(0, partner_node_id, required),
		(2, violation_type, required),
		(4, evidence, required),
	},
	(11, AuditDiscrepancy) => {
		(0, partner_node_id, required),
		(2, ledger_address, required),
		(4, discrepancy_type, required),
	},
	(12, FeeAssessed) => {
		(0, deposit_pubkey, required),
		(2, amount, required),
		(4, timestamp, required),
	},
	(13, TransferLocked) => {
		(0, deposit_pubkey, required),
		(2, amount, required),
		(4, transfer_id, required),
	},
	(14, TransferCompleted) => {
		(0, deposit_pubkey, required),
		(2, amount, required),
		(4, transfer_id, required),
	},
	(15, TransferFailed) => {
		(0, deposit_pubkey, required),
		(2, amount, required),
		(4, transfer_id, required),
	},
	(16, AuditCompleted) => {
		(0, partner_node_id, required),
		(2, ledger_id, required),
		(4, violations_found, required),
	},
	(17, CommitmentEnhanced) => {
		(0, partner_node_id, required),
		(2, ledger_hash, required),
		(4, commitment_number, required),
		(6, reserves_outputs_count, required),
	},
	(18, ReservesSpendReady) => {
		(0, vote_round_id, required),
		(2, operator_id, required),
		(4, reserves_id, required),
		(6, signed_tx_bytes, required),
		(8, conforming_votes, required),
		(10, threshold, required),
	},
	(19, RecoveryClaimReady) => {
		(0, operator_id, required),
		(2, reserves_id, required),
	},
	(20, RecoveryClaimCompleted) => {
		(0, old_operator, required),
		(2, reserves_id, required),
		(4, new_operator, required),
		(6, claim_txid, required),
		(8, confirmation_block, required),
	},
	(21, RecoveryNonCompliant) => {
		(0, operator_id, required),
		(2, reserves_id, required),
		(4, non_conforming_votes, required),
		(6, total_votes, required),
	},
	(22, UncreditedPaymentAccusation) => {
		(0, operator, required),
		(2, partner, required),
		(4, payment_hash, required),
		(6, deposit_pubkey, required),
		(8, amount_msat, required),
		(10, settlement_sequence, required),
	}
);
