//! DEP-06 lottery recovery voters: the members, minus the original operator, of the latest
//! QuorumBegin the original operator authored at or below the dispute's fork point. Pinned by
//! the vector shared with cl-deposits (inspect/vectors/lottery_recovery_voters.txt there);
//! `REGEN_VECTORS=1` rewrites it. Each case lists abstract updates; both implementations build
//! them and must derive the same voters and threshold.

use bitcoin::secp256k1::{PublicKey, Secp256k1, SecretKey};
use deposits_core::messages::{LedgerOperation, QuorumMemberRef};
use deposits_core::rotation_order::lottery_recovery_voters;
use deposits_core::tlv::TlvEncode;
use deposits_core::types::SignedLedgerUpdate;

fn pk(i: u8) -> PublicKey {
    PublicKey::from_secret_key(&Secp256k1::new(), &SecretKey::from_slice(&[i; 32]).unwrap())
}

fn upd(seq: u64, author: u8, op: &LedgerOperation) -> SignedLedgerUpdate {
    SignedLedgerUpdate {
        message: op.tlv_encode(),
        message_type: op.message_type(),
        operator_id: pk(author),
        ledger_id: [2; 32],
        sequence_number: seq,
        previous_hash: [0; 32],
        content_hash: [0; 32],
        block_height: 100,
        block_hash: [0; 32],
        operator_signature: [0; 64],
        cosignatures: Vec::new(),
    }
}

fn qb(members: &[u8]) -> LedgerOperation {
    LedgerOperation::QuorumBegin {
        reserves_id: "x".into(),
        spending_txid: [0; 32],
        new_outpoint_txid: [0; 32],
        new_outpoint_vout: 0,
        amount: 0,
        quorum_expiry: 1000,
        ledger_hash: [0; 32],
        quorum_members: members
            .iter()
            .map(|i| QuorumMemberRef::new(pk(*i), String::new()))
            .collect(),
        collateral_amount: 0,
        protocol_version: Some("cltv-offset-v2".into()),
        exit_cutoff_height: None,
        exit_outputs: Vec::new(),
        splice_in_outpoint: None,
        splice_in_amount: None,
    }
}

fn open() -> LedgerOperation {
    LedgerOperation::LedgerOpen {
        operator_id: pk(1),
        reserves_id: "x".into(),
        genesis_block: 0,
        reserves_amount: 0,
        collateral_amount: 0,
    }
}

fn enter(last_valid: u64) -> LedgerOperation {
    LedgerOperation::DisputeEnter {
        last_valid_sequence: last_valid,
        reason: "test".into(),
        anchor_block_hash: None,
        anchor_block_height: None,
    }
}

/// (name, updates as (seq, author key byte, kind, args)). Key byte 1 is the original operator.
#[allow(clippy::type_complexity)]
fn cases() -> Vec<(&'static str, Vec<(u64, u8, &'static str, Vec<u64>)>)> {
    vec![
        (
            "plain",
            vec![
                (0, 1, "open", vec![]),
                (1, 1, "qb", vec![1, 2, 3, 4]),
                (5, 2, "enter", vec![4]),
            ],
        ),
        (
            "later_qb_past_fork_point",
            vec![
                (0, 1, "open", vec![]),
                (1, 1, "qb", vec![1, 2, 3, 4]),
                (6, 1, "qb", vec![1, 5, 6]),
                (7, 2, "enter", vec![4]),
            ],
        ),
        (
            "qb_by_another_author",
            vec![
                (0, 1, "open", vec![]),
                (1, 1, "qb", vec![1, 2, 3, 4, 5, 6]),
                (3, 7, "qb", vec![7, 8, 9]),
                (4, 2, "enter", vec![3]),
            ],
        ),
        (
            "lowest_fork_point_wins",
            vec![
                (0, 1, "open", vec![]),
                (1, 1, "qb", vec![1, 2, 3]),
                (4, 1, "qb", vec![1, 4, 5, 6, 7]),
                (9, 2, "enter", vec![8]),
                (9, 3, "enter", vec![2]),
            ],
        ),
        (
            "no_dispute",
            vec![
                (0, 1, "open", vec![]),
                (1, 1, "qb", vec![1, 2, 3]),
                (8, 1, "qb", vec![1, 4, 5]),
            ],
        ),
    ]
}

fn build(us: &[(u64, u8, &'static str, Vec<u64>)]) -> Vec<SignedLedgerUpdate> {
    us.iter()
        .map(|(seq, author, kind, args)| {
            let op = match *kind {
                "open" => open(),
                "qb" => qb(&args.iter().map(|a| *a as u8).collect::<Vec<_>>()),
                "enter" => enter(args[0]),
                _ => unreachable!(),
            };
            upd(*seq, *author, &op)
        })
        .collect()
}

#[test]
fn recovery_voters_vector_is_pinned() {
    let mut out = vec!["# DEP-06 lottery recovery voters (shared cl-deposits / deposits-rust), generated by deposits-rust".to_string()];
    out.push("# key i is the public key of the secret [i; 32]".into());
    for (name, us) in cases() {
        out.push(format!("case {name}"));
        for (seq, author, kind, args) in &us {
            out.push(format!(
                "upd {seq} {} {kind}{}",
                hex::encode(pk(*author).serialize()),
                args.iter()
                    .map(|a| if *kind == "qb" {
                        format!(" {}", hex::encode(pk(*a as u8).serialize()))
                    } else {
                        format!(" {a}")
                    })
                    .collect::<String>()
            ));
        }
        let (voters, t) = lottery_recovery_voters(&build(&us)).unwrap();
        out.push(format!(
            "voters{}",
            voters
                .iter()
                .map(|v| format!(" {}", hex::encode(v.serialize())))
                .collect::<String>()
        ));
        out.push(format!("threshold {t}"));
    }
    let text = out.join("\n") + "\n";
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/vectors/lottery_recovery_voters.txt"
    );
    if std::env::var("REGEN_VECTORS").is_ok() {
        std::fs::write(path, &text).unwrap();
    }
    assert_eq!(
        std::fs::read_to_string(path).unwrap(),
        text,
        "regenerate with REGEN_VECTORS=1"
    );
}
