//! DEP-10 offer cosign digest, pinned by the vector shared with cl-deposits
//! (inspect/vectors/offer_cosign.txt there). REGEN_VECTORS=1 rewrites it.

use bitcoin::secp256k1::{PublicKey, Secp256k1, SecretKey};
use deposits_core::signature_utils::offer_cosign_signing_message;

#[test]
fn offer_cosign_vector_is_pinned() {
    let pk = |i: u8| {
        PublicKey::from_secret_key(&Secp256k1::new(), &SecretKey::from_slice(&[i; 32]).unwrap())
    };
    let cases: Vec<(&str, [u8; 32], PublicKey, &str, u32, [u8; 32])> = vec![
        (
            "p2tr",
            [0x11; 32],
            pk(1),
            "bcrt1pmfr3p9j00pfxjh0zmgp99y8zftmd3s5pmedqhyptwy6lm87hf5sspknck9",
            4990,
            [0x22; 32],
        ),
        (
            "p2wpkh",
            [0x33; 32],
            pk(2),
            "bc1qar0srrr7xfkvy5l643lydnw9re59gtzzwf5mdq",
            0x0102_0304,
            [0x44; 32],
        ),
    ];
    let ledger = "a1".repeat(32);
    let mut out = vec![
        "# DEP-10 offer cosign digest (shared), generated by deposits-rust; key i = secret [i;32]"
            .to_string(),
    ];
    for (name, offer_id, op, addr, deadline, mlh) in cases {
        let d = offer_cosign_signing_message(&ledger, &offer_id, &op, addr, deadline, &mlh);
        out.push(format!(
            "case {name}\nledger {ledger}\noffer {}\noperator {}\naddress {addr}\ndeadline {deadline}\nmember_ledger_hash {}\ndigest {}",
            hex::encode(offer_id),
            hex::encode(op.serialize()),
            hex::encode(mlh),
            hex::encode(d)
        ));
    }
    let text = out.join("\n") + "\n";
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/vectors/offer_cosign.txt"
    );
    if std::env::var("REGEN_VECTORS").is_ok() {
        std::fs::write(path, &text).unwrap();
    }
    assert_eq!(
        std::fs::read_to_string(path).unwrap(),
        text,
        "regenerate with REGEN_VECTORS=1"
    );
}
