server {
    listen 443 ssl;

    ssl_certificate /certs/nip05.crt;
    ssl_certificate_key /certs/nip05.key;

    location /.well-known/ {
        root /usr/share/nginx/html;
        default_type application/json;
        add_header Access-Control-Allow-Origin *;
    }
}
